<?php

/**
 * @file
 * This is a Drupal 10 settings.ddev.php file automatically generated by DDEV.
 *
 * DDEV manages this file and may delete or overwrite it unless this
 * comment, marked with #ddev-generated, is removed. It is recommended
 * that you leave this file alone.
 */

$config['system.logging']['error_level'] = 'verbose';
// ----- Chargement .env -----
$env_file = DRUPAL_ROOT . '/.env.local';

if (is_readable($env_file)) {
  $env = parse_ini_file($env_file, false, INI_SCANNER_RAW);
  if ($env !== false) {
    foreach ($env as $key => $value) {
      // Trim pour éviter BOM/espace
      $value = is_string($value) ? trim($value) : $value;
      $_ENV[$key] = $value;
      $_SERVER[$key] = $value;
      putenv($key . '=' . $value);
    }
  } else {
    trigger_error("Impossible de parser $env_file (format INI attendu).", E_USER_WARNING);
  }
} else {
  trigger_error("Fichier .env introuvable ou illisible à $env_file.", E_USER_WARNING);
}
// ----- fin chargement .env -----

$host = $_ENV['DRUPAL_DB_HOST'] ?? 'db';
$port = $_ENV['DRUPAL_DB_PORT'] ?? '3306';
$driver = $_ENV['DRUPAL_DB_DRIVER'] ?? 'mysql';

$databases['default']['default']['database'] = $_ENV['DRUPAL_DB_NAME'] ?? "db";
$databases['default']['default']['username'] = $_ENV['DRUPAL_DB_USER'] ?? "db";
$databases['default']['default']['password'] = $_ENV['DRUPAL_DB_PASSWORD'] ?? "db";
$databases['default']['default']['host'] = $host;
$databases['default']['default']['port'] = $port;
$databases['default']['default']['driver'] = $driver;

$settings['hash_salt'] = 'cbaa7b4742644368696a09106fac69f9b9d055373b8a7b2898ee61f3cb994591';

// Recommended setting for Drupal 10 only
$settings['state_cache'] = TRUE;

// This will prevent Drupal from setting read-only permissions on sites/default.
$settings['skip_permissions_hardening'] = TRUE;

// This will ensure the site can only be accessed through the intended host
// names. Additional host patterns can be added for custom configurations.
$settings['trusted_host_patterns'] = ['.*'];

// Set $settings['config_sync_directory'] if not set in settings.php.
if (empty($settings['config_sync_directory'])) {
  $settings['config_sync_directory'] = 'sites/default/files/sync';
}

// Override drupal/symfony_mailer default config to use Mailpit.
$config['symfony_mailer.settings']['default_transport'] = 'sendmail';
$config['symfony_mailer.mailer_transport.sendmail']['plugin'] = 'smtp';
$config['symfony_mailer.mailer_transport.sendmail']['configuration']['user'] = '';
$config['symfony_mailer.mailer_transport.sendmail']['configuration']['pass'] = '';
$config['symfony_mailer.mailer_transport.sendmail']['configuration']['host'] = 'localhost';
$config['symfony_mailer.mailer_transport.sendmail']['configuration']['port'] = '1025';

// Enable verbose logging for errors.
// https://www.drupal.org/forum/support/post-installation/2018-07-18/enable-drupal-8-backend-errorlogdebugging-mode
$config['system.logging']['error_level'] = 'verbose';
